GET http://localhost:6060/api/v1/tours HTTP/1.1
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYzdmNTg4NmQ3ZTM4NzVmYWZkMjFiNiIsImlhdCI6MTY3NDA3NjAwMiwiZXhwIjoxNjc0NjgwODAyfQ.-P7e8hHtvqkuHtE6J51lXAH1RXy3bWoaSiwoWMWw-8Y

###
POST http://localhost:6065/api/v1/tours HTTP/1.1
Content-Type: application/json

{
    "name":"The Snow Adventurer"
    
}

###
GET http://localhost:6060/api/v1/tours/ssfdsfgdfsfsd HTTP/1.1

###
PATCH http://localhost:6060/api/v1/tours/63ab1edb44ef79d9a27abd HTTP/1.1
Content-Type: application/json

{
    "name":"testing893",
    "price": 4444,
    "rating": 4.7
}

###
DELETE http://localhost:6060/api/v1/tours/63ab1edb44ef79d9a27abd33 HTTP/1.1