GET http://localhost:6060/api/v1/tours HTTP/1.1

###
POST http://localhost:6060/api/v1/tours HTTP/1.1
Content-Type: application/json

{
    "name":"testing4e6",
    "duration": 10,
    "difficuilty": "easy",
    "price": 40004535,
    "rating": 4.7
}

###
GET http://localhost:6060/api/v1/tours/639c9f7cff59d2ec89ae350f HTTP/1.1

###
PATCH http://localhost:6060/api/v1/tours/639c9f7cff59d2ec89ae350f HTTP/1.1
Content-Type: application/json

{
    "name":"testing893",
    "price": 4444,
    "rating": 4.7
}

###
DELETE http://localhost:6060/api/v1/tours/639c9f7cff59d2ec89ae350f HTTP/1.1