
GET http://localhost:6060/api/v1/tours HTTP/1.1

###
POST http://localhost:6060/api/v1/tours HTTP/1.1
Content-Type: application/json

{
    "name":"teat Zamdhf",
    "duration":9,
    "maxGroupSize":20,
    "difficulty":"easy",
    "ratingsAverage":8,
    "ratingsQuantity":54,
    "price":1197,
    "summary":"Living the life of Wanderlust in the US' most beatiful cities",
    "description":"Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat lorem ipsum dolor sit amet.\nConsectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur, nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat!",
    "imageCover":"tour-4-cover.jpg",
    "images":["tour-4-1.jpg","tour-4-2.jpg","tour-4-3.jpg"]
}

###
GET http://localhost:6060/api/v1/tours/63ab1edb44ef79d9a27abd33e HTTP/1.1

###
PATCH http://localhost:6060/api/v1/tours/63ab1edb44ef79d9a27abd HTTP/1.1
Content-Type: application/json

{
    "name":"testing893",
    "price": 4444,
    "rating": 4.7
}

###
DELETE http://localhost:6060/api/v1/tours/63ab1edb44ef79d9a27abd33 HTTP/1.1