GET http://localhost:6060/api/v1/users HTTP/1.1

###
POST http://localhost:6060/api/v1/users/signup HTTP/1.1
Content-Type: application/json

{
    "name":"testing405",
    "email": "test405@gmail.com",
    "password": "praise2test",
    "passwordConfirm": "praise2test"
}

###
POST http://localhost:6060/api/v1/users/login HTTP/1.1
Content-Type: application/json

{
    "email": "test404@gmail.com",
    "password": "praise2test"
}

###
GET http://localhost:6060/api/v1/users/ HTTP/1.1
